spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_demo?useSSL=false&serverTimezone=UTC
    username: root
    password: "@mysqlgamerpro09"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

app:
    security:
      jwt:
        secret: ${JWT_SECRET:REPLACE_WITH_BASE64_25BIT_SECRET}
        expiration-ms: ${JWT_EXP_MS:7200000}
server:
    port: 8080